service: nimo-http-api-gateway

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  stage: dev

resources:
  Resources:
    SharedHttpApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: nimo-http-api
        ProtocolType: HTTP

outputs:
  HttpApiId:
    Value: !Ref SharedHttpApi
    Export:
      Name: NimoSharedHttpApiId
