service: notifier

provider: ${file(../../serverless.base.yml):provider}
plugins: ${file(../../serverless.base.yml):plugins}

custom:
  serverless-offline:
    httpPort: 3003
    lambdaPort: 4003
    reloadHandler: ${file(../../serverless.base.yml):custom.serverless-offline.reloadHandler}
  esbuild: ${file(../../serverless.base.yml):custom.esbuild}

functions:
  main:
    handler: src/handler.handler
    events:
      - httpApi:
          method: ANY
          path: /notifier
      - httpApi:
          method: ANY
          path: /notifier/{proxy+}
