service: notifier

provider: ${file(../../serverless.base.yml):provider}
plugins: ${file(../../serverless.base.yml):plugins}

custom:
  serverless-offline:
    httpPort: 3009
    lambdaPort: 4009
    reloadHandler: ${file(../../serverless.base.yml):custom.serverless-offline.reloadHandler}
  esbuild: ${file(../../serverless.base.yml):custom.esbuild}

	
functions:
  emailSQS:
    handler: src/handler.handler
    events:
      - sqs: arn:aws:sqs:ap-southeast-2:205930627026:email.fifo

